"""add outbox_messages

Revision ID: 5f677b54688c
Revises: f656e26e3e9d
Create Date: 2026-07-26 10:21:04.786312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f677b54688c'
down_revision: Union[str, None] = 'f656e26e3e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('payment_id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=True),
    sa.Column('update_link', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_messages_customer_id'), 'outbox_messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_payment_id'), 'outbox_messages', ['payment_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_sent_at'), 'outbox_messages', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_messages_sent_at'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_payment_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_customer_id'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
