"""add sim_pending_webhooks

Revision ID: f656e26e3e9d
Revises: 33c7439e4044
Create Date: 2026-07-25 23:02:36.116348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f656e26e3e9d'
down_revision: Union[str, None] = '33c7439e4044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_pending_webhooks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('deliver_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_pending_webhooks_deliver_at'), 'sim_pending_webhooks', ['deliver_at'], unique=False)
    op.create_index(op.f('ix_sim_pending_webhooks_event_id'), 'sim_pending_webhooks', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_pending_webhooks_event_id'), table_name='sim_pending_webhooks')
    op.drop_index(op.f('ix_sim_pending_webhooks_deliver_at'), table_name='sim_pending_webhooks')
    op.drop_table('sim_pending_webhooks')
    # ### end Alembic commands ###
